name: Install and basic test on push on master and develop

on:
  push:
    branches:
      - master
      - develop

jobs:
  install-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Create uv environment
        run: uv venv

      - name: Install package (local)
        run: uv pip install .

      - name: Install test runner
        run: uv pip install pytest

      - name: Run test suite
        run: uv run pytest -q tests/ --ignore tests/test_run.py
